---
title: "Teaching"
---

Following are the courses I have taught. All the courses are taught at Iowa State University unless otherwise mentioned.

-   Spring 2025

    -   (Course Instructor) Introduction to Business Statistics I

<!-- (https://drive.google.com/file/d/19sp9Y6NZfVWDlL0-AvAFiOCdkMjfrkHA/view?usp=sharing){target="_blank"} -->

<!-- -->

-   Fall 2024

    -   (Course Instructor) Introduction to Business Statistics I

-   Spring 2024

    -   (Course Instructor) Introduction to Business Statistics I

-   Fall 2023

    -   (Course Instructor) Introduction to Business Statistics I

-   Spring 2023

    -   (Course Instructor) Introduction to Business Statistics I

-   Fall 2022

    -   (Course Instructor) Introduction to Business Statistics I

-   Summer 2022

    -   (Course Instructor) Introduction to Business Statistics II

-   Spring 2022 [(Teaching Excellence Award)](https://www.parchment.com/u/award/8c2806c139618f48aa4d798354edb686){target="_blank"}

    -   (Course Instructor) Introduction to Business Statistics I

-   Fall 2021

    -   (Course Instructor) Introduction to Business Statistics I

-   Spring 2021

    -   (Teaching Assistant) STAT 474/574: Introduction to Bayesian Data Analysis
    -   (Grading Assistant) STAT 104: Introduction to Statistics

-   Fall 2020

    -   (Teaching Assistant) STAT 587: Statistical Methods for Research Workers
    -   (Lab Instructor) STAT 326: Introduction to Business Statistics II

-   Spring 2020

    -   (Teaching Assistant) STAT 404: Regression for Social and Behavioral Research
    -   (Lab Instructor) STAT 326: Introduction to Business Statistics II

-   Fall 2019

    -   (Teaching Assistant) STAT 404: Regression for Social and Behavioral Research
    -   (Grading Assistant) STAT 226: Introduction to Business Statistics I

-   Spring 2019 (San Diego State University)

    -   (Lab Instructor) STAT 250: Statistical Principles and Practices

-   Fall 2018 (San Diego State University)

    -   (Lab Instructor) STAT 250: Statistical Principles and Practices

-   Spring 2018 (San Diego State University)

    -   (Grading Assistant) STAT 596: Advanced Topics in Statistics
